---
- name: Fetch kubeconfig from control plane to bastion
  hosts: control_plane
  become: true
  tasks:
    - name: Copy kubeconfig to temporary location
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: /tmp/admin.conf
        flat: yes

- name: Install kubeconfig on bastion
  hosts: bastion
  connection: local
  become: false

  tasks:
    - name: Ensure .kube directory exists
      file:
        path: /home/ubuntu/.kube
        state: directory
        mode: '0700'

    - name: Move kubeconfig into place
      copy:
        src: /tmp/admin.conf
        dest: /home/ubuntu/.kube/config
        mode: '0600'
